/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/GameScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/GameScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LoadingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/GameScreen${`?${string}` | `#${string}` | ''}` | `/components/LoadingScreen${`?${string}` | `#${string}` | ''}` | `/components/LoginScreen${`?${string}` | `#${string}` | ''}` | `/components/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/lib/storage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/GameScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownInputParams; };
    }
  }
}
